name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Docker Compose Action
        with:
          compose-file: ./docker-compose.yml

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: security-checker security:check composer.lock

      # Runs a set of commands using the runners shell
      - name: testing
        run: composer test
